// ============================================================================
// top: top-level integration module for a 3-axis BLDC/PMSM servo controller.
//
// Architecture overview:
//   • FPGA acts as SPI **master** to an STM32H7 (high-level control MCU).
//     Every tick (20 kHz), the FPGA sends encoder + ADC data and receives
//     PWM duty commands back.
//   • FPGA also acts as SPI **master** to three STM32G4 chips, each of
//     which provides 2-channel ADC current measurements for one motor axis.
//     ADC reads are triggered at the PWM center point for optimal sampling.
//   • Per axis the FPGA instantiates:
//       – 2 × quadrature decoders (motor encoder + output/load encoder)
//       – 3 × center-aligned PWM generators (phases A, B, C)
//       – 3 × dead-time inserters (half-bridge shoot-through protection)
//   • A central register file (system_storage) acts as the shared data bus
//     between the SPI exchange FSM and all peripheral sub-modules.
//
// Clock: 27 MHz on-board oscillator (Gowin FPGA).
// Reset: active-low, directly from push-button btn1.
// ============================================================================
module top (
    input  logic        clk,       // 27 MHz system clock
    input  logic        btn1,      // Active-low reset push-button
    
    // SPI to STM32H7 (FPGA = Master) — full-duplex data exchange every tick
    output logic        spi_cs_n,  // Chip-select to STM32 (directly triggers EXTI for DMA setup)
    output logic        spi_sck,   // SPI clock generated by the FPGA
    output logic        spi_mosi,  // FPGA → STM32 data (encoder positions, ADC currents)
    input  logic        spi_miso,  // STM32 → FPGA data (PWM duty commands, enable flags)

    // SPI to G4 ADC front-ends (3 independent buses, one per axis, FPGA = Master)
    output logic [2:0]  g4_cs_n,   // Chip-selects for 3 × STM32G4 ADC slaves
    output logic [2:0]  g4_sck,    // SPI clocks for 3 × G4 buses
    input  logic [2:0]  g4_miso,   // ADC data coming back from each G4

    // Incremental encoder inputs (3 axes × 2 encoders: motor-side and output-side)
    input  logic [2:0]  enc_m_a,   // Motor encoder phase-A for axes 0/1/2
    input  logic [2:0]  enc_m_b,   // Motor encoder phase-B for axes 0/1/2
    input  logic [2:0]  enc_o_a,   // Output encoder phase-A for axes 0/1/2
    input  logic [2:0]  enc_o_b,   // Output encoder phase-B for axes 0/1/2

    // PWM gate-drive outputs (3 axes × 3 phases × high-side/low-side)
    output logic [2:0]  gate_a_h,  // Phase-A high-side gate for axes 0/1/2
    output logic [2:0]  gate_a_l,  // Phase-A low-side  gate for axes 0/1/2
    output logic [2:0]  gate_b_h,  // Phase-B high-side gate for axes 0/1/2
    output logic [2:0]  gate_b_l,  // Phase-B low-side  gate for axes 0/1/2
    output logic [2:0]  gate_c_h,  // Phase-C high-side gate for axes 0/1/2
    output logic [2:0]  gate_c_l,  // Phase-C low-side  gate for axes 0/1/2
    
    // Debug LEDs on the development board (directly active-low)
    output logic [5:0]  led
);

    // Map the push-button directly to active-low reset
    logic rst_n;
    assign rst_n = btn1;

    // ==========================================
    // BYTE SWAP UTILITY
    // ==========================================
    // The STM32 is little-endian while SPI shifts MSB-first. This helper
    // reverses the byte order of a 32-bit word so that the STM32's DMA
    // receives / sends data in the correct byte lane order.
    function automatic logic [31:0] swap32(logic [31:0] v);
        return {v[7:0], v[15:8], v[23:16], v[31:24]};
    endfunction

    // ==========================================
    // PARAMETERS
    // ==========================================
    localparam AXIS_COUNT    = 3;       // Number of motor axes in the system
    localparam DATA_WIDTH    = 256;     // Bits per SPI frame to/from STM32 (8 × 32-bit words)
    
    // PWM carrier frequency: 20 kHz (inaudible — no coil whine)
    // Calculation: 27 000 000 / 20 000 = 1350 counts per half-period
    localparam PWM_PERIOD    = 16'd1350; // Triangle counter ceiling for center-aligned PWM
    localparam TICK_PERIOD   = 16'd1349; // Tick timer reload value (generates 20 kHz strobe)
    
    localparam DT_TICKS      = 8'd50;   // Dead-time duration in clock cycles (~1.85 µs at 27 MHz)

    // SPI bus to STM32H7: CLK_DIV=0 → SCK = clk/2 = 13.5 MHz (maximum speed)
    localparam SPI_CLK_DIV   = 0;       // SCK half-period divisor
    localparam SPI_CS_WAIT   = 50;      // Clocks to hold CS low before first SCK edge (STM32 DMA setup time)

    // SPI bus to G4 ADC slaves: slightly slower, with short CS lead-in
    localparam G4_DATA_WIDTH = 32;      // 32 bits per ADC SPI transaction (2 × 16-bit packed currents)
    localparam G4_CLK_DIV    = 1;       // SCK = clk/4 = 6.75 MHz
    localparam G4_CS_WAIT    = 14;      // CS-to-SCK setup time for G4

    // ==========================================
    // INTERNAL BUS (register bridge between FSM and system_storage)
    // ==========================================
    logic        bus_we;     // Write enable: pulsed for one clock per write
    logic [7:0]  bus_addr;   // Address: upper nibble = axis, lower nibble = register
    logic [31:0] bus_wdata;  // Write data
    logic [31:0] bus_rdata;  // Read data (combinational from system_storage)

    // ==========================================
    // FLAT WIRES (directly connect sub-modules to system_storage ports)
    // ==========================================
    logic [2:0]  axis_en;    // Per-axis enable flags (from storage regs → PWM generators)

    // PWM duty-cycle values written by the STM32 into storage, read by PWM generators
    logic [15:0] pwm_a_0, pwm_a_1, pwm_a_2; // Phase-A duty for each axis
    logic [15:0] pwm_b_0, pwm_b_1, pwm_b_2; // Phase-B duty for each axis
    logic [15:0] pwm_c_0, pwm_c_1, pwm_c_2; // Phase-C duty for each axis

    // Encoder feedback signals going INTO system_storage (read-only for STM32)
    logic [31:0] enc_m_pos_0, enc_m_pos_1, enc_m_pos_2; // Motor encoder positions
    logic [31:0] enc_o_pos_0, enc_o_pos_1, enc_o_pos_2; // Output encoder positions
    logic [31:0] enc_m_per_0, enc_m_per_1, enc_m_per_2; // Motor encoder periods (inverse speed)
    logic [31:0] enc_o_per_0, enc_o_per_1, enc_o_per_2; // Output encoder periods
    logic [2:0]  enc_m_dir, enc_o_dir;                   // Direction flags
    logic [2:0]  enc_m_idx, enc_o_idx;                   // Index-found latches

    // ADC current data received from the three G4 slaves (packed 2×16 bit)
    logic [31:0] adc_data_0, adc_data_1, adc_data_2;

    // Center-event pulses from each axis's phase-A PWM generator.
    // These fire once per PWM period at the triangle peak — the ideal instant
    // to sample phase currents (switching noise is minimal at center of ON-time).
    logic center_evt_0, center_evt_1, center_evt_2;

    // G4 ADC SPI handshake signals (one set per axis)
    logic g4_start_0, g4_start_1, g4_start_2; // Trigger an ADC SPI read
    logic g4_busy_0,  g4_busy_1,  g4_busy_2;  // SPI master busy flag
    logic g4_done_0,  g4_done_1,  g4_done_2;  // SPI transaction complete pulse
    logic g4_mosi_0,  g4_mosi_1,  g4_mosi_2;  // MOSI outputs (unused — we only read from G4)

    // Launch an ADC SPI read on each center event, but only if the SPI master is idle
    assign g4_start_0 = center_evt_0 & ~g4_busy_0;
    assign g4_start_1 = center_evt_1 & ~g4_busy_1;
    assign g4_start_2 = center_evt_2 & ~g4_busy_2;

    // ==========================================
    // 1. STORAGE (centralized register file)
    // ==========================================
    // Bridges the internal bus to all encoder, ADC, PWM duty and enable signals.
    // The exchange FSM writes PWM commands here; encoder/ADC data is read from here.
    system_storage #(.AXIS_COUNT(AXIS_COUNT)) storage (
        .clk(clk), .rst_n(rst_n),
        .write_en(bus_we), .addr(bus_addr), .wdata(bus_wdata), .rdata(bus_rdata),
        .enables(axis_en),
        .pwm_a_0(pwm_a_0), .pwm_a_1(pwm_a_1), .pwm_a_2(pwm_a_2),
        .pwm_b_0(pwm_b_0), .pwm_b_1(pwm_b_1), .pwm_b_2(pwm_b_2),
        .pwm_c_0(pwm_c_0), .pwm_c_1(pwm_c_1), .pwm_c_2(pwm_c_2),
        .enc_motor_pos_0(enc_m_pos_0),   .enc_motor_pos_1(enc_m_pos_1),   .enc_motor_pos_2(enc_m_pos_2),
        .enc_output_pos_0(enc_o_pos_0),  .enc_output_pos_1(enc_o_pos_1),  .enc_output_pos_2(enc_o_pos_2),
        .enc_motor_per_0(enc_m_per_0),   .enc_motor_per_1(enc_m_per_1),   .enc_motor_per_2(enc_m_per_2),
        .enc_output_per_0(enc_o_per_0),  .enc_output_per_1(enc_o_per_1),  .enc_output_per_2(enc_o_per_2),
        .enc_motor_dir(enc_m_dir),       .enc_output_dir(enc_o_dir),
        .enc_motor_idx(enc_m_idx),       .enc_output_idx(enc_o_idx),
        .adc_data_0(adc_data_0),         .adc_data_1(adc_data_1),         .adc_data_2(adc_data_2)
    );

    // ==========================================
    // 2. AXIS 0 — encoders, PWM, dead-time
    // ==========================================

    // Motor-side quadrature decoder (Z-index and homing not used — tied off)
    quadrature_decoder dec_m0 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_m_a[0]), .b_in(enc_m_b[0]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_m_pos_0), .period(enc_m_per_0),
        .dir_fwd(enc_m_dir[0]), .index_found(enc_m_idx[0])
    );
    // Output-side (load) quadrature decoder
    quadrature_decoder dec_o0 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_o_a[0]), .b_in(enc_o_b[0]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_o_pos_0), .period(enc_o_per_0),
        .dir_fwd(enc_o_dir[0]), .index_found(enc_o_idx[0])
    );

    // Raw (pre-deadtime) PWM signals for axis 0's three phases
    logic p_a0, p_b0, p_c0;

    // Phase A — also generates the center_event used for ADC trigger
    pwm_generator  g_a0 (.clk(clk),.rst_n(rst_n),.enable(axis_en[0]),.period(PWM_PERIOD),.duty(pwm_a_0),.pwm_out(p_a0),.center_event(center_evt_0));
    deadtime       d_a0 (.clk(clk),.rst_n(rst_n),.pwm_in(p_a0),.dt_ticks(DT_TICKS),.pwm_h(gate_a_h[0]),.pwm_l(gate_a_l[0]));
    // Phase B — center_event unused (only one trigger needed per axis)
    pwm_generator  g_b0 (.clk(clk),.rst_n(rst_n),.enable(axis_en[0]),.period(PWM_PERIOD),.duty(pwm_b_0),.pwm_out(p_b0),.center_event());
    deadtime       d_b0 (.clk(clk),.rst_n(rst_n),.pwm_in(p_b0),.dt_ticks(DT_TICKS),.pwm_h(gate_b_h[0]),.pwm_l(gate_b_l[0]));
    // Phase C
    pwm_generator  g_c0 (.clk(clk),.rst_n(rst_n),.enable(axis_en[0]),.period(PWM_PERIOD),.duty(pwm_c_0),.pwm_out(p_c0),.center_event());
    deadtime       d_c0 (.clk(clk),.rst_n(rst_n),.pwm_in(p_c0),.dt_ticks(DT_TICKS),.pwm_h(gate_c_h[0]),.pwm_l(gate_c_l[0]));

    // ==========================================
    // 2. AXIS 1 — encoders, PWM, dead-time
    // ==========================================

    // Motor-side quadrature decoder
    quadrature_decoder dec_m1 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_m_a[1]), .b_in(enc_m_b[1]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_m_pos_1), .period(enc_m_per_1),
        .dir_fwd(enc_m_dir[1]), .index_found(enc_m_idx[1])
    );
    // Output-side quadrature decoder
    quadrature_decoder dec_o1 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_o_a[1]), .b_in(enc_o_b[1]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_o_pos_1), .period(enc_o_per_1),
        .dir_fwd(enc_o_dir[1]), .index_found(enc_o_idx[1])
    );

    // Raw PWM signals for axis 1
    logic p_a1, p_b1, p_c1;
    // Phase A (center_event triggers axis-1 ADC read)
    pwm_generator  g_a1 (.clk(clk),.rst_n(rst_n),.enable(axis_en[1]),.period(PWM_PERIOD),.duty(pwm_a_1),.pwm_out(p_a1),.center_event(center_evt_1));
    deadtime       d_a1 (.clk(clk),.rst_n(rst_n),.pwm_in(p_a1),.dt_ticks(DT_TICKS),.pwm_h(gate_a_h[1]),.pwm_l(gate_a_l[1]));
    // Phase B
    pwm_generator  g_b1 (.clk(clk),.rst_n(rst_n),.enable(axis_en[1]),.period(PWM_PERIOD),.duty(pwm_b_1),.pwm_out(p_b1),.center_event());
    deadtime       d_b1 (.clk(clk),.rst_n(rst_n),.pwm_in(p_b1),.dt_ticks(DT_TICKS),.pwm_h(gate_b_h[1]),.pwm_l(gate_b_l[1]));
    // Phase C
    pwm_generator  g_c1 (.clk(clk),.rst_n(rst_n),.enable(axis_en[1]),.period(PWM_PERIOD),.duty(pwm_c_1),.pwm_out(p_c1),.center_event());
    deadtime       d_c1 (.clk(clk),.rst_n(rst_n),.pwm_in(p_c1),.dt_ticks(DT_TICKS),.pwm_h(gate_c_h[1]),.pwm_l(gate_c_l[1]));

    // ==========================================
    // 2. AXIS 2 — encoders, PWM, dead-time
    // ==========================================

    // Motor-side quadrature decoder
    quadrature_decoder dec_m2 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_m_a[2]), .b_in(enc_m_b[2]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_m_pos_2), .period(enc_m_per_2),
        .dir_fwd(enc_m_dir[2]), .index_found(enc_m_idx[2])
    );
    // Output-side quadrature decoder
    quadrature_decoder dec_o2 (
        .clk(clk), .rst_n(rst_n),
        .a_in(enc_o_a[2]), .b_in(enc_o_b[2]), .z_in(1'b0),
        .set_zero(1'b0), .homing_mode(1'b0),
        .position(enc_o_pos_2), .period(enc_o_per_2),
        .dir_fwd(enc_o_dir[2]), .index_found(enc_o_idx[2])
    );

    // Raw PWM signals for axis 2
    logic p_a2, p_b2, p_c2;
    // Phase A (center_event triggers axis-2 ADC read)
    pwm_generator  g_a2 (.clk(clk),.rst_n(rst_n),.enable(axis_en[2]),.period(PWM_PERIOD),.duty(pwm_a_2),.pwm_out(p_a2),.center_event(center_evt_2));
    deadtime       d_a2 (.clk(clk),.rst_n(rst_n),.pwm_in(p_a2),.dt_ticks(DT_TICKS),.pwm_h(gate_a_h[2]),.pwm_l(gate_a_l[2]));
    // Phase B
    pwm_generator  g_b2 (.clk(clk),.rst_n(rst_n),.enable(axis_en[2]),.period(PWM_PERIOD),.duty(pwm_b_2),.pwm_out(p_b2),.center_event());
    deadtime       d_b2 (.clk(clk),.rst_n(rst_n),.pwm_in(p_b2),.dt_ticks(DT_TICKS),.pwm_h(gate_b_h[2]),.pwm_l(gate_b_l[2]));
    // Phase C
    pwm_generator  g_c2 (.clk(clk),.rst_n(rst_n),.enable(axis_en[2]),.period(PWM_PERIOD),.duty(pwm_c_2),.pwm_out(p_c2),.center_event());
    deadtime       d_c2 (.clk(clk),.rst_n(rst_n),.pwm_in(p_c2),.dt_ticks(DT_TICKS),.pwm_h(gate_c_h[2]),.pwm_l(gate_c_l[2]));

    // ==========================================
    // 3. G4 ADC SPI (3 independent SPI masters running in parallel)
    // ==========================================
    // Each instance reads 32 bits (2 × 16-bit phase currents) from one G4.
    // tx_data is all zeros because we only receive from the ADC slaves.

    // Axis 0 ADC SPI master
    spi_master #(.DATA_WIDTH(G4_DATA_WIDTH),.CLK_DIV(G4_CLK_DIV),.CS_WAIT(G4_CS_WAIT)) g4_spi_0 (
        .clk(clk), .rst_n(rst_n),
        .start(g4_start_0), .tx_data(32'd0),
        .rx_data(adc_data_0), .busy(g4_busy_0), .done(g4_done_0),
        .spi_cs_n(g4_cs_n[0]), .spi_sck(g4_sck[0]),
        .spi_mosi(g4_mosi_0), .spi_miso(g4_miso[0])
    );

    // Axis 1 ADC SPI master
    spi_master #(.DATA_WIDTH(G4_DATA_WIDTH),.CLK_DIV(G4_CLK_DIV),.CS_WAIT(G4_CS_WAIT)) g4_spi_1 (
        .clk(clk), .rst_n(rst_n),
        .start(g4_start_1), .tx_data(32'd0),
        .rx_data(adc_data_1), .busy(g4_busy_1), .done(g4_done_1),
        .spi_cs_n(g4_cs_n[1]), .spi_sck(g4_sck[1]),
        .spi_mosi(g4_mosi_1), .spi_miso(g4_miso[1])
    );

    // Axis 2 ADC SPI master
    spi_master #(.DATA_WIDTH(G4_DATA_WIDTH),.CLK_DIV(G4_CLK_DIV),.CS_WAIT(G4_CS_WAIT)) g4_spi_2 (
        .clk(clk), .rst_n(rst_n),
        .start(g4_start_2), .tx_data(32'd0),
        .rx_data(adc_data_2), .busy(g4_busy_2), .done(g4_done_2),
        .spi_cs_n(g4_cs_n[2]), .spi_sck(g4_sck[2]),
        .spi_mosi(g4_mosi_2), .spi_miso(g4_miso[2])
    );

    // ==========================================
    // 4. SPI CORE (main data link to STM32H7)
    // ==========================================
    // Full-duplex exchange: FPGA sends 256 bits of sensor data, simultaneously
    // receives 256 bits of PWM commands from the STM32.
    logic                   spi_start, spi_done, spi_busy;
    logic [DATA_WIDTH-1:0]  spi_tx_data; // Packed TX frame to STM32
    logic [DATA_WIDTH-1:0]  spi_rx_data; // Packed RX frame from STM32

    spi_master #(
        .DATA_WIDTH (DATA_WIDTH),
        .CLK_DIV    (SPI_CLK_DIV),
        .CS_WAIT    (SPI_CS_WAIT)
    ) spi_core (
        .clk(clk), .rst_n(rst_n),
        .start(spi_start), .tx_data(spi_tx_data), .rx_data(spi_rx_data),
        .busy(spi_busy), .done(spi_done),
        .spi_cs_n(spi_cs_n), .spi_sck(spi_sck),
        .spi_mosi(spi_mosi), .spi_miso(spi_miso)
    );

    // ==========================================
    // 5. TICK TIMER (20 kHz periodic strobe)
    // ==========================================
    // Generates a single-cycle 'tick' pulse at the PWM carrier rate.
    // This tick triggers one SPI exchange cycle with the STM32 per PWM period.
    logic [15:0] tick_timer;
    logic        tick;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tick_timer <= 16'd0;
            tick       <= 1'b0;
        end else begin
            if (tick_timer >= TICK_PERIOD) begin
                tick_timer <= 16'd0;   // Reset counter
                tick       <= 1'b1;    // Emit a one-clock tick pulse
            end else begin
                tick_timer <= tick_timer + 16'd1;
                tick       <= 1'b0;    // No tick this clock
            end
        end
    end

    // ==========================================
    // 6. EXCHANGE STATE MACHINE
    // ==========================================
    // Orchestrates the periodic data exchange with the STM32:
    //   1. Wait for tick (20 kHz strobe).
    //   2. Read encoder positions and ADC data from system_storage.
    //   3. Pack them into a 256-bit TX frame and start the SPI transfer.
    //   4. When SPI completes, unpack the 256-bit RX frame.
    //   5. Write the received PWM duty / enable values back into system_storage.
    //   6. Return to idle and wait for the next tick.
    //
    // TX frame layout (FPGA → STM32), 8 × 32-bit words, MSB-first:
    //   Word 7: 0xAA55AA55  — sync/magic header
    //   Word 6: ADC data axis 0
    //   Word 5: Encoder position axis 0
    //   Word 4: ADC data axis 1
    //   Word 3: Encoder position axis 1
    //   Word 2: ADC data axis 2
    //   Word 1: Encoder position axis 2
    //   Word 0: Sequence counter (monotonically increasing)
    //
    // RX frame layout (STM32 → FPGA), 8 × 32-bit words:
    //   Word 7 (rxw0): 0xDEADBEEF magic — used for link_ok validation
    //   Words 6..1 (rxw1..rxw6): packed PWM duties + enable flags for 3 axes
    //   Word 0 (rxw7): reserved / unused
    logic [31:0] seq_counter;   // Monotonically increasing frame counter sent to STM32
    logic [4:0]  state;         // FSM state (0..20)
    logic        link_ok;       // Set when the STM32 responds with the correct magic header

    // Unpacked 32-bit words received from STM32 (byte-swapped)
    logic [31:0] rxw0, rxw1, rxw2, rxw3, rxw4, rxw5, rxw6, rxw7;

    // Snapshot registers: encoder and ADC values read from storage before packing
    logic [31:0] tx_enc0, tx_enc1, tx_enc2;
    logic [31:0] tx_adc0, tx_adc1, tx_adc2;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            spi_start   <= 0;
            bus_we      <= 0;
            state       <= 5'd0;
            spi_tx_data <= '0;
            bus_addr    <= 8'd0;
            bus_wdata   <= 32'd0;
            seq_counter <= 32'd0;
            link_ok     <= 0;
            rxw0<=0; rxw1<=0; rxw2<=0; rxw3<=0;
            rxw4<=0; rxw5<=0; rxw6<=0; rxw7<=0;
            tx_enc0<=0; tx_enc1<=0; tx_enc2<=0;
            tx_adc0<=0; tx_adc1<=0; tx_adc2<=0;
        end else begin
            spi_start <= 0;   // Default: no SPI start pulse
            bus_we    <= 0;   // Default: no register write

            case (state)
                // ---- IDLE: wait for the next 20 kHz tick and SPI not busy ----
                5'd0: begin
                    if (tick && !spi_busy) begin
                        bus_addr <= 8'h04;       // Set address to read enc_motor_pos axis 0
                        state    <= 5'd1;
                    end
                end

                // ---- States 1–6: sequentially read encoder positions and ADC data ----
                // Each state latches the data that was addressed in the PREVIOUS state,
                // then sets up the address for the NEXT read.

                5'd1: begin tx_enc0 <= bus_rdata; bus_addr <= 8'h14; state <= 5'd2; end  // Latch motor encoder pos[0], request pos[1]
                5'd2: begin tx_enc1 <= bus_rdata; bus_addr <= 8'h24; state <= 5'd3; end  // Latch motor encoder pos[1], request pos[2]
                5'd3: begin tx_enc2 <= bus_rdata; bus_addr <= 8'h09; state <= 5'd4; end  // Latch motor encoder pos[2], request ADC[0]
                5'd4: begin tx_adc0 <= bus_rdata; bus_addr <= 8'h19; state <= 5'd5; end  // Latch ADC[0], request ADC[1]
                5'd5: begin tx_adc1 <= bus_rdata; bus_addr <= 8'h29; state <= 5'd6; end  // Latch ADC[1], request ADC[2]
                5'd6: begin tx_adc2 <= bus_rdata;                    state <= 5'd7; end  // Latch ADC[2]

                // ---- State 7: pack the TX frame and fire the SPI transfer ----
                5'd7: begin
                    seq_counter <= seq_counter + 1; // Increment frame sequence number

                    // Build the 256-bit TX payload (all words byte-swapped for STM32 endianness).
                    // If ADC data is zero (no reading yet), substitute mid-scale (2048) as a safe default.
                    spi_tx_data[255:224] <= swap32(32'hAA55AA55);                                             // Sync header
                    spi_tx_data[223:192] <= swap32(tx_adc0 == 32'd0 ? {16'd2048, 16'd2048} : tx_adc0);       // ADC axis 0
                    spi_tx_data[191:160] <= swap32(tx_enc0);                                                  // Encoder axis 0
                    spi_tx_data[159:128] <= swap32(tx_adc1 == 32'd0 ? {16'd2048, 16'd2048} : tx_adc1);       // ADC axis 1
                    spi_tx_data[127:96]  <= swap32(tx_enc1);                                                  // Encoder axis 1
                    spi_tx_data[95:64]   <= swap32(tx_adc2 == 32'd0 ? {16'd2048, 16'd2048} : tx_adc2);       // ADC axis 2
                    spi_tx_data[63:32]   <= swap32(tx_enc2);                                                  // Encoder axis 2
                    spi_tx_data[31:0]    <= swap32(seq_counter);                                              // Sequence number
                    spi_start <= 1;       // Trigger the SPI master
                    state     <= 5'd8;
                end

                // ---- State 8: wait for SPI to finish, then unpack RX data ----
                5'd8: begin
                    if (spi_done) begin
                        // Byte-swap each received 32-bit word to native FPGA order
                        rxw0 <= swap32(spi_rx_data[255:224]); // Expected: 0xDEADBEEF magic
                        rxw1 <= swap32(spi_rx_data[223:192]); // Axis 0 PWM A[15:0] + PWM B[31:16]
                        rxw2 <= swap32(spi_rx_data[191:160]); // Axis 0 PWM C[15:0] + enable[31:16]
                        rxw3 <= swap32(spi_rx_data[159:128]); // Axis 1 PWM A[15:0] + PWM B[31:16]
                        rxw4 <= swap32(spi_rx_data[127:96]);  // Axis 1 PWM C[15:0] + enable[31:16]
                        rxw5 <= swap32(spi_rx_data[95:64]);   // Axis 2 PWM A[15:0] + PWM B[31:16]
                        rxw6 <= swap32(spi_rx_data[63:32]);   // Axis 2 PWM C[15:0] + enable[31:16]
                        rxw7 <= swap32(spi_rx_data[31:0]);    // Reserved / unused

                        // Validate that the STM32 sent the correct magic header
                        link_ok <= (swap32(spi_rx_data[255:224]) == 32'hDEADBEEF);
                        state   <= 5'd9;
                    end
                end

                // ---- States 9–20: write unpacked RX words into system_storage ----
                // Four writes per axis: reg0 = enable, reg1 = PWM-A, reg2 = PWM-B, reg3 = PWM-C.
                // Upper 16 bits are zeroed (only lower 16 bits carry meaningful data).

                // Axis 0 registers
                5'd9:  begin bus_we<=1; bus_addr<=8'h00; bus_wdata<={16'd0,rxw2[31:16]}; state<=5'd10; end // Axis 0 enable (bit 0)
                5'd10: begin bus_we<=1; bus_addr<=8'h01; bus_wdata<={16'd0,rxw1[15:0]};  state<=5'd11; end // Axis 0 PWM phase-A duty
                5'd11: begin bus_we<=1; bus_addr<=8'h02; bus_wdata<={16'd0,rxw1[31:16]}; state<=5'd12; end // Axis 0 PWM phase-B duty
                5'd12: begin bus_we<=1; bus_addr<=8'h03; bus_wdata<={16'd0,rxw2[15:0]};  state<=5'd13; end // Axis 0 PWM phase-C duty

                // Axis 1 registers
                5'd13: begin bus_we<=1; bus_addr<=8'h10; bus_wdata<={16'd0,rxw4[31:16]}; state<=5'd14; end // Axis 1 enable
                5'd14: begin bus_we<=1; bus_addr<=8'h11; bus_wdata<={16'd0,rxw3[15:0]};  state<=5'd15; end // Axis 1 PWM phase-A duty
                5'd15: begin bus_we<=1; bus_addr<=8'h12; bus_wdata<={16'd0,rxw3[31:16]}; state<=5'd16; end // Axis 1 PWM phase-B duty
                5'd16: begin bus_we<=1; bus_addr<=8'h13; bus_wdata<={16'd0,rxw4[15:0]};  state<=5'd17; end // Axis 1 PWM phase-C duty

                // Axis 2 registers
                5'd17: begin bus_we<=1; bus_addr<=8'h20; bus_wdata<={16'd0,rxw6[31:16]}; state<=5'd18; end // Axis 2 enable
                5'd18: begin bus_we<=1; bus_addr<=8'h21; bus_wdata<={16'd0,rxw5[15:0]};  state<=5'd19; end // Axis 2 PWM phase-A duty
                5'd19: begin bus_we<=1; bus_addr<=8'h22; bus_wdata<={16'd0,rxw5[31:16]}; state<=5'd20; end // Axis 2 PWM phase-B duty
                5'd20: begin bus_we<=1; bus_addr<=8'h23; bus_wdata<={16'd0,rxw6[15:0]};  state<=5'd0;  end // Axis 2 PWM phase-C duty → back to IDLE

                // Safety: return to idle on any unexpected state
                default: state <= 5'd0;
            endcase
        end
    end

    // ==========================================
    // 7. DEBUG LEDs
    // ==========================================
    // Simple visual indicators for bench debugging (accent active-low LEDs).

    // Heartbeat counter: bit 24 toggles at ~0.8 Hz (27 MHz / 2^25) for a visible blink
    logic [24:0] heartbeat;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) heartbeat <= 25'd0;
        else heartbeat <= heartbeat + 25'd1;
    end

    assign led[0] = ~(pwm_a_0 == 16'd13500); // Lights when axis-0 phase-A duty is NOT at a specific test value
    assign led[1] = ~(pwm_b_0 == 16'd13500); // Same for phase-B
    assign led[2] = ~(pwm_c_0 == 16'd13500); // Same for phase-C
    assign led[3] = ~axis_en[0];              // Lights when axis 0 is DISABLED (inverted logic)
    assign led[4] = ~link_ok;                 // Lights when the STM32 link is DOWN (no valid magic received)
    assign led[5] = ~heartbeat[24];           // Blinks slowly (~0.8 Hz) — proves the FPGA clock is running

endmodule